### ISSUE TITLE
Mechanism to check client & server app compatibility

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#223]
See also #183 - which has potential relevance/overlap.

Now that we have a server 'app version'. We should also add (at the Naked Objects Client level) the ability to specify a Client _Application_ version (as distinct from the Naked Objects Client version), together with:

- A standard API by which app developers may easily add in their own function for testing client and server _application_ compatibility, and advising the user if the client must be updated and how (by refreshing).

**Comment by scascarini** [comment]
Current implementaion needs to be made generic and moved into framework (see above). At the moment, by default, dev builds do not check version, test and prod do. The version is expected to be the same (no semver checking) because test and prod builds are always built and deployed with the same version in client and server.

**Comment by scascarini** [comment]
Displayed heading and message is here (may need refining) https://github.com/MetalUp/Express/blob/main/Client/src/app/app.component.html#L16
